name: CI


on:
  push:
    branches:
      - main
  pull_request:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/actions/build

      - name: lint
        run: ruff check --fix --unsafe-fixes --target-version py311 app

  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/actions/build

      - name: pyright
        uses: jakebailey/pyright-action@v2
